version: "3"

services:
  rabbit-mq:
    image: rabbitmq:management
    container_name: custom-rabbit-mq
    volumes:
      - ./lib/rabbitmq/etc:/etc/rabbitmq
      - ./lib/rabbitmq/data:/var/lib/rabbitmq
      - ./lib/rabbitmq/logs:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
